// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnlhxoblmhzapzktotvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubGh4b2JsbWh6YXB6a3RvdHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODI5MDgsImV4cCI6MjA2NTk1ODkwOH0.drlRUTDlxrxWMj12a7Evfo9UJmE5R1Mz6vVf4lVhMVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});